[package]
name = "apollo-router-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
apollo-router = "2.3.0"
async-trait = "0.1"
schemars = "0.8"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower = { version = "0.5", features = ["full"] }
