package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"errors"
	"log/slog"
	"review-subgraph/graph/model"
)

// FindReviewByID is the resolver for the findReviewByID field.
func (r *entityResolver) FindReviewByID(ctx context.Context, id string) (*model.Review, error) {
	review := model.Review{
		Product: new(model.Product),
		User:    new(model.User),
	}
	err := r.Datastore.QueryRowContext(ctx, `
		SELECT r.id, r.rating, r.comment, r.product_sku, r.user_id
		FROM "review" r
		WHERE r.id = $1;`,
		id,
	).Scan(&review.ID, &review.Rating, &review.Comment, &review.Product.Sku, &review.User.ID)
	if err != nil {
		slog.Error("review not found", slog.Any("error", err))
		return nil, errors.New("review not found")
	}

	return &review, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
