// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewProduct struct {
	Name        string  `json:"name"`
	Price       int32   `json:"price"`
	Description *string `json:"description,omitempty"`
}

type Product struct {
	Sku         string    `json:"sku"`
	Name        string    `json:"name"`
	Price       int32     `json:"price"`
	Description string    `json:"description"`
	Reviews     []*Review `json:"reviews"`
}

func (Product) IsEntity() {}

type Query struct {
}

type Review struct {
	ID string `json:"id"`
}

func (Review) IsEntity() {}
