package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"errors"
	"log/slog"
	"product-subgraph/graph/model"
)

// FindProductBySku is the resolver for the findProductBySku field.
func (r *entityResolver) FindProductBySku(ctx context.Context, sku string) (*model.Product, error) {
	var product model.Product
	err := r.Datastore.QueryRowContext(ctx, `
		SELECT p.sku, p.name, p.price, p.description
		FROM "product" p
		WHERE p.sku = $1;`,
		sku,
	).Scan(&product.Sku, &product.Name, &product.Price, &product.Description)
	if err != nil {
		slog.Error("product not found", slog.Any("error", err))
		return nil, errors.New("product not found")
	}

	return &product, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
