// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type NewReview struct {
	Rating     int32  `json:"rating"`
	Comment    string `json:"comment"`
	ProductSku string `json:"productSku"`
}

type Product struct {
	Sku string `json:"sku"`
}

func (Product) IsEntity() {}

type Query struct {
}

type Review struct {
	ID      string   `json:"id"`
	Rating  int32    `json:"rating"`
	Comment string   `json:"comment"`
	Product *Product `json:"product"`
	User    *User    `json:"user"`
}

func (Review) IsEntity() {}

type User struct {
	ID string `json:"id"`
}

func (User) IsEntity() {}
