package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"
	"errors"
	"log/slog"
	"user-subgraph/graph/model"
)

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	var user model.User
	err := r.Datastore.QueryRowContext(ctx, `
		SELECT u.id, u.name, u.access_type FROM "user" u
		WHERE u.id = $1;`,
		id,
	).Scan(&user.ID, &user.Name, &user.Type)
	if err != nil {
		slog.Error("user not found", slog.Any("error", err), slog.String("userID", id))
		return nil, errors.New("user not found")
	}

	return &user, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
